//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSimDotNet {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InSimDotNet.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InSim is already connected.
        /// </summary>
        internal static string InSimConnectedMessage {
            get {
                return ResourceManager.GetString("InSimConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lost connection to InSim..
        /// </summary>
        internal static string InSimConnectionLostMessage {
            get {
                return ResourceManager.GetString("InSimConnectionLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not connect to InSim.
        /// </summary>
        internal static string InSimCouldNotConnectMessage {
            get {
                return ResourceManager.GetString("InSimCouldNotConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid InSim version.
        /// </summary>
        internal static string InSimInvalidVersionMessage {
            get {
                return ResourceManager.GetString("InSimInvalidVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a InSim is not connected.
        /// </summary>
        internal static string InSimNotConnectedMessage {
            get {
                return ResourceManager.GetString("InSimNotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot connect to InSim Relay with UDP.
        /// </summary>
        internal static string InSimRelayUdpErrorMessage {
            get {
                return ResourceManager.GetString("InSimRelayUdpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IS_AXM too many objects set.
        /// </summary>
        internal static string IsAxmInfoErrorMessage {
            get {
                return ResourceManager.GetString("IsAxmInfoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IS_REO too many PLIDs set.
        /// </summary>
        internal static string IsReoPlidErrorMessage {
            get {
                return ResourceManager.GetString("IsReoPlidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Packet size was not a multiple of four.
        /// </summary>
        internal static string PacketSizeErrorMessage {
            get {
                return ResourceManager.GetString("PacketSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TCP Receive Error: {0}.
        /// </summary>
        internal static string TcpSocketDebugErrorMessage {
            get {
                return ResourceManager.GetString("TcpSocketDebugErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UDP Receive Error: {0}.
        /// </summary>
        internal static string UdpSocketDebugErrorMessage {
            get {
                return ResourceManager.GetString("UdpSocketDebugErrorMessage", resourceCulture);
            }
        }
    }
}
